name: Main to Docs Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into docs
        run: |
          echo "zero"
          git fetch origin refs/heads/docs:refs/remotes/origin/docs
          echo "one"
          git checkout docs
          echo "two"
          git merge --ff-only origin/main || echo "Nothing to merge"
          echo "three"
          if ! git diff --quiet; then
            git commit -am "Sync main -> docs [skip ci]"
            echo "four"
            git push origin docs
            echo "five"
          else
            echo "No changes to push"
